### ISSUE TITLE
[CustomerAPI]

### ISSUE THREAD

**Issue by dhinus** [contactlab/contacthub-sdk-nodejs#8]
[Trello card](https://trello.com/c/586a8d3c1c1f5ce21a8a3a51/)

## requirements
Improve the current implementation (written ~ 2 months ago) and check it works correctly with the latest version of the API. Also add the missing Customer methods.

## specs

- refactor using ES6 classes (to be defined)
- remove references to `_embedded`
- add an e2e test creating and reading a Customer with all possible attributes
- add `getCustomersByExternalId()` (returning Array)
- add `patchCustomer()` method
- add `query` param to getCustomers()

## sub-issues

- [x] refactor using ES6 classes #9 
- [x] remove references to _embedded #10 **[ascariandrea]**
- [x] add e2e test with complex Customer object #11 **[dhinus]**
- [x] add getCustomersByExternalId() #12 
- [x] add patchCustomer() method #13 **[ascariandrea]**
- [x] add query param to getCustomers() #14 **[dhinus]**
